[build]
  base = "."
  publish = "public"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "14" # Asegúrate de usar la versión de Node.js que necesitas

[dev]
  command = "npm start"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200